---
- name: Install apt repository key
  apt_key:
    url: 'https://www.liveconfig.com/liveconfig.key'
    state: present

- name: Install apt repository
  apt_repository:
    repo: 'deb http://repo.liveconfig.com/debian/ main main'
    filename: 'liveconfig'
    update_cache: yes
    state: present
