---
- name: Converge
  hosts: all
  become: yes

  vars:

  pre_tasks:
    - name: Install dependencies
      package:
        name:
          - gpg
          - ca-certificates
        state: present

  roles:
    - role: serverfriendsorg.liveconfig
